services:
  - type: web
    name: FirePointSys
    env: python
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11
